services:
  rabbitmq:
    image: rabbitmq:3.8.0-management-alpine
    container_name: rabbitmq-ciee
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq:/etc/rabbitmq/

  postgres:
    image: postgres:16.3
    container_name: postgres-ciee
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: poc

  mongodb:
    image: mongo:latest
    container_name: mongodb-ciee
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"